
INSERT INTO public.plan_days (dia, mes, semana, semana_titulo, semana_frase, capitulo) VALUES
  (1, 1, 1, 'Criar as bases do teu negócio', 'Para onde vai a nossa atenção, flui a nossa energia.', 'Prospecção e Posicionamento'),
  (2, 1, 1, 'Criar as bases do teu negócio', 'Para onde vai a nossa atenção, flui a nossa energia.', 'Comportamento dos Proprietários'),
  (3, 1, 1, 'Criar as bases do teu negócio', 'Para onde vai a nossa atenção, flui a nossa energia.', 'Comportamento dos agentes imobiliários'),
  (4, 1, 1, 'Criar as bases do teu negócio', 'Para onde vai a nossa atenção, flui a nossa energia.', 'Script das chamadas telefônicas aos proprietários'),
  (5, 1, 1, 'Criar as bases do teu negócio', 'Para onde vai a nossa atenção, flui a nossa energia.', 'Tarefas de alta e baixa rentabilidade'),
  (6, 1, 2, 'Torna-te conhecedor da tua área de posicionamento', 'Não saia para o mar sem saber o que vai pescar.', 'Posicionamento'),
  (7, 1, 2, 'Torna-te conhecedor da tua área de posicionamento', 'Não saia para o mar sem saber o que vai pescar.', 'Conceito de Posicionamento Imobiliário'),
  (8, 1, 2, 'Torna-te conhecedor da tua área de posicionamento', 'Não saia para o mar sem saber o que vai pescar.', 'Levantamento de área'),
  (9, 1, 2, 'Torna-te conhecedor da tua área de posicionamento', 'Não saia para o mar sem saber o que vai pescar.', 'Posicionamento Demográfico'),
  (10, 1, 2, 'Torna-te conhecedor da tua área de posicionamento', 'Não saia para o mar sem saber o que vai pescar.', 'Primeira visita de potencial venda'),
  (11, 1, 3, 'Começar a encher a tua prateleira', 'O sucesso é mais atitude do que aptidão.', 'Exclusividade & Serviço de excelência'),
  (12, 1, 3, 'Começar a encher a tua prateleira', 'O sucesso é mais atitude do que aptidão.', 'Plano de divulgação do imóvel'),
  (13, 1, 3, 'Começar a encher a tua prateleira', 'O sucesso é mais atitude do que aptidão.', 'Vantagens do proprietário não estar presente na visita'),
  (14, 1, 3, 'Começar a encher a tua prateleira', 'O sucesso é mais atitude do que aptidão.', 'Quando o cliente procura um imóvel que "não existe"'),
  (15, 1, 3, 'Começar a encher a tua prateleira', 'O sucesso é mais atitude do que aptidão.', 'Visita com os compradores'),
  (16, 2, 4, 'Cimenta o teu negócio', 'Quem domina a captação, domina o mercado.', 'Apresentação de Plano de Marketing'),
  (17, 2, 4, 'Cimenta o teu negócio', 'Quem domina a captação, domina o mercado.', 'Relatório de acompanhamento'),
  (18, 2, 4, 'Cimenta o teu negócio', 'Quem domina a captação, domina o mercado.', 'Apresentação do estudo de mercado'),
  (19, 2, 4, 'Cimenta o teu negócio', 'Quem domina a captação, domina o mercado.', 'Compradores e fechamento'),
  (20, 2, 4, 'Cimenta o teu negócio', 'Quem domina a captação, domina o mercado.', 'Estratégia Comercial'),
  (21, 2, 5, 'Não deixes de semear', 'A tua vida é demasiado grande para te permitires jogar pequeno.', 'A envolvência influencia o valor'),
  (22, 2, 5, 'Não deixes de semear', 'A tua vida é demasiado grande para te permitires jogar pequeno.', 'Vender imóveis pelo primeiro preço'),
  (23, 2, 5, 'Não deixes de semear', 'A tua vida é demasiado grande para te permitires jogar pequeno.', 'Fechando Negócio'),
  (24, 2, 5, 'Não deixes de semear', 'A tua vida é demasiado grande para te permitires jogar pequeno.', 'A importância do proprietário não estar presente'),
  (25, 2, 5, 'Não deixes de semear', 'A tua vida é demasiado grande para te permitires jogar pequeno.', 'Estudo de mercado na visita'),
  (26, 2, 6, 'Desafia-te', 'O que não te desafia não te transforma.', 'Sinais do pré-fechamento'),
  (27, 2, 6, 'Desafia-te', 'O que não te desafia não te transforma.', 'Ficha de visita'),
  (28, 2, 6, 'Desafia-te', 'O que não te desafia não te transforma.', 'Indícios de compra'),
  (29, 2, 6, 'Desafia-te', 'O que não te desafia não te transforma.', 'Técnica de apresentação da proposta'),
  (30, 2, 6, 'Desafia-te', 'O que não te desafia não te transforma.', 'Gestão de tempo e conclusão'),
  (31, 2, 7, 'Relembra a tua existência', 'Do que estás à espera para viveres o teu sonho?', 'Revisão e prática livre'),
  (32, 2, 7, 'Relembra a tua existência', 'Do que estás à espera para viveres o teu sonho?', 'Revisão e prática livre'),
  (33, 2, 7, 'Relembra a tua existência', 'Do que estás à espera para viveres o teu sonho?', 'Revisão e prática livre'),
  (34, 2, 7, 'Relembra a tua existência', 'Do que estás à espera para viveres o teu sonho?', 'Revisão e prática livre'),
  (35, 2, 7, 'Relembra a tua existência', 'Do que estás à espera para viveres o teu sonho?', 'Revisão e prática livre — encerramento do plano')
ON CONFLICT (dia) DO UPDATE SET mes=EXCLUDED.mes, semana=EXCLUDED.semana, semana_titulo=EXCLUDED.semana_titulo, semana_frase=EXCLUDED.semana_frase, capitulo=EXCLUDED.capitulo;

DELETE FROM public.plan_tasks;

INSERT INTO public.plan_tasks (dia, ordem, descricao) VALUES
  (1, 1, 'Briefing 9:30 com o gestor (definir objetivos da semana)'),
  (1, 2, 'Criar scripts de contatos'),
  (1, 3, 'Contactar 10 potenciais e inserir no Excel'),
  (2, 1, 'Briefing com o gestor'),
  (2, 2, 'Contactar 10 CIPs (conhecidos) e inserir no Excel'),
  (2, 3, 'Criar página no Facebook / Instagram / LinkedIn'),
  (2, 4, 'Montar dossier de apresentação'),
  (2, 5, 'Levantar imobiliárias da área'),
  (2, 6, 'Criar scripts de prospecção'),
  (2, 7, 'Iniciar a área de posicionamento'),
  (3, 1, 'Briefing com o gestor'),
  (3, 2, 'Contactar 10 CIPs e inserir no Excel'),
  (3, 3, 'Explorar as plataformas RE/MAX (sites e redes)'),
  (3, 4, 'Post no Facebook divulgando o novo projeto'),
  (3, 5, 'Levantar 10 proprietários na internet'),
  (4, 1, 'Briefing com o gestor'),
  (4, 2, 'Levantar portais/sites e criar contas'),
  (4, 3, 'Prospecção telefônica a 10 proprietários'),
  (4, 4, 'Levantar imóveis à venda e vendidos da área'),
  (4, 5, 'Contactar 10 CIPs'),
  (4, 6, 'Reciclagem de objeções de captação'),
  (4, 7, 'Acompanhar colega numa captação'),
  (5, 1, 'Briefing com o gestor'),
  (5, 2, 'Levantar 10 proprietários na internet'),
  (5, 3, 'Prospecção telefônica a 10 proprietários'),
  (5, 4, 'Contactar 10 CIPs no maxwork'),
  (5, 5, 'Levantar imóveis fora da rede RE/MAX'),
  (5, 6, 'Acompanhar colega numa visita'),
  (5, 7, 'Enviar email aos CIPs'),
  (6, 1, 'Inserir post nas redes (2ªf)'),
  (6, 2, 'Briefing com o gestor'),
  (6, 3, '2h de posicionamento na área'),
  (6, 4, 'Levantar 5 FSBOs e contactar'),
  (6, 5, 'Levantamento de área 1/30'),
  (6, 6, 'Entregar 10 cartões do líder em mãos'),
  (6, 7, 'Verificar alertas de portais (FSBO)'),
  (6, 8, 'Contactar 10 CIPs por messenger'),
  (6, 9, 'Enviar relatório diário'),
  (7, 1, 'Briefing com o gestor'),
  (7, 2, '2h de posicionamento na área'),
  (7, 3, 'Levantar 5 FSBOs e contactar'),
  (7, 4, 'Levantamento de área 2/30'),
  (7, 5, 'Entregar 10 cartões em mãos'),
  (7, 6, 'Reciclagem / teatros de venda'),
  (7, 7, 'Verificar alertas de portais (FSBO)'),
  (7, 8, 'Acompanhar colega numa visita'),
  (7, 9, 'Contactar 10 CIPs por messenger'),
  (7, 10, 'Enviar relatório diário'),
  (8, 1, 'Briefing com o gestor'),
  (8, 2, '2h de posicionamento na área'),
  (8, 3, 'Levantar 5 FSBOs e contactar'),
  (8, 4, 'Levantamento de área 3/30'),
  (8, 5, 'Entregar 10 cartões em mãos'),
  (8, 6, 'Acompanhar colega numa captação'),
  (8, 7, 'Verificar alertas de portais (FSBO)'),
  (8, 8, '2h de seguimento à base de dados'),
  (8, 9, 'Enviar relatório diário'),
  (9, 1, 'Briefing com o gestor'),
  (9, 2, '2h de posicionamento na área'),
  (9, 3, 'Levantamento de área 4/30'),
  (9, 4, 'Reciclagem de objeções'),
  (9, 5, 'Entregar 10 cartões em mãos'),
  (9, 6, 'Preparar flyer/carta de apresentação'),
  (9, 7, 'Bloco de tempo para seguimento a FSBOs'),
  (9, 8, 'Contactar 10 CIPs por messenger'),
  (9, 9, 'Enviar relatório diário'),
  (10, 1, 'Briefing com o gestor'),
  (10, 2, '2h de posicionamento na área'),
  (10, 3, 'Levantamento de área 5/30'),
  (10, 4, 'Entregar 10 cartões em mãos'),
  (10, 5, '2h de seguimento à base de dados'),
  (10, 6, 'Inserir post nas redes'),
  (10, 7, 'Verificar flyers/cartas'),
  (10, 8, 'Preparar blocos de notas'),
  (10, 9, 'Enviar relatório diário'),
  (11, 1, 'Inserir post nas redes (2ªf)'),
  (11, 2, 'Briefing com o gestor'),
  (11, 3, '2h de posicionamento na área'),
  (11, 4, 'Levantamento de área 6/30'),
  (11, 5, 'Entregar 10 cartões em mãos'),
  (11, 6, 'Entregar 25 flyers a residentes'),
  (11, 7, 'Verificar alertas de portais (FSBO)'),
  (11, 8, 'Levantar dias comemorativos e preparar posts'),
  (11, 9, 'Enviar relatório diário'),
  (12, 1, 'Briefing com o gestor'),
  (12, 2, '2h de posicionamento na área'),
  (12, 3, 'Levantamento de área 7/30'),
  (12, 4, 'Entregar 10 cartões em mãos'),
  (12, 5, 'Entregar 25 flyers a residentes'),
  (12, 6, 'Teatros de venda (3ªf)'),
  (12, 7, 'Contactar 10 CIPs na base'),
  (12, 8, 'Contactar 10 CIPs por messenger'),
  (12, 9, 'Enviar relatório diário'),
  (13, 1, 'Briefing com o gestor'),
  (13, 2, '2h de posicionamento na área'),
  (13, 3, 'Levantamento de área 8/30'),
  (13, 4, 'Saída de equipe (ação de rua)'),
  (13, 5, 'Entregar 10 cartões em mãos'),
  (13, 6, 'Entregar 25 flyers a residentes'),
  (13, 7, 'Iniciar entrega de blocos de notas no comércio'),
  (13, 8, '2h de seguimento à base de dados'),
  (13, 9, 'Acompanhar colega em visita com compradores'),
  (13, 10, 'Enviar relatório diário'),
  (14, 1, 'Briefing com o gestor'),
  (14, 2, '2h de posicionamento na área'),
  (14, 3, 'Levantamento de área 9/30'),
  (14, 4, 'Saída de equipe (ação de rua)'),
  (14, 5, 'Entregar 10 cartões em mãos'),
  (14, 6, 'Entregar 25 flyers a residentes'),
  (14, 7, 'Post à procura de captações'),
  (14, 8, 'Continuar entrega de blocos de notas'),
  (14, 9, 'Acompanhar colega numa APS (estudo de mercado)'),
  (14, 10, 'Enviar relatório diário'),
  (15, 1, 'Briefing com o gestor'),
  (15, 2, '2h de posicionamento na área'),
  (15, 3, 'Levantamento de área 10/30'),
  (15, 4, 'Entregar 10 cartões em mãos'),
  (15, 5, 'Entregar 25 flyers a residentes'),
  (15, 6, '2h de seguimento à base de dados'),
  (15, 7, 'Enviar 10 sms a CIPs'),
  (15, 8, 'Continuar entrega de blocos de notas'),
  (15, 9, 'Enviar relatório diário'),
  (16, 1, 'Inserir post nas redes (2ªf)'),
  (16, 2, 'Briefing com o gestor'),
  (16, 3, '2h de posicionamento na área'),
  (16, 4, 'Levantamento de área 11/30'),
  (16, 5, 'Entregar 10 cartões em mãos'),
  (16, 6, 'Entregar 25 flyers a residentes'),
  (16, 7, 'Verificar alertas de portais (FSBO)'),
  (16, 8, 'Levantar placas da concorrência'),
  (16, 9, 'Enviar relatório diário'),
  (17, 1, 'Briefing com o gestor'),
  (17, 2, '2h de posicionamento na área'),
  (17, 3, 'Preparar posts de dias comemorativos'),
  (17, 4, 'Teatros de venda (3ªf)'),
  (17, 5, 'Levantamento de área 12/30'),
  (17, 6, 'Entregar 10 cartões em mãos'),
  (17, 7, 'Entregar 25 flyers a residentes'),
  (17, 8, 'Acompanhar colega na escala'),
  (17, 9, 'Enviar 10 sms a CIPs'),
  (17, 10, 'Enviar relatório diário'),
  (18, 1, 'Briefing com o gestor'),
  (18, 2, '2h de posicionamento na área'),
  (18, 3, 'Inserir post nas redes'),
  (18, 4, 'Levantamento de área 13/30'),
  (18, 5, 'Entregar 10 cartões em mãos'),
  (18, 6, 'Entregar 25 flyers a residentes'),
  (18, 7, 'Continuar levantamento de imóveis da concorrência'),
  (18, 8, '2h de seguimento à base de dados'),
  (18, 9, 'Enviar relatório diário'),
  (19, 1, 'Briefing com o gestor'),
  (19, 2, '2h de posicionamento na área'),
  (19, 3, 'Levantamento de área 14/30'),
  (19, 4, 'Entregar 10 cartões em mãos'),
  (19, 5, 'Entregar 25 flyers a residentes'),
  (19, 6, 'Preparar revista/flyer de parceria com o comércio'),
  (19, 7, 'Enviar relatório diário'),
  (20, 1, 'Briefing com o gestor'),
  (20, 2, '2h de posicionamento na área'),
  (20, 3, 'Levantamento de área 15/30'),
  (20, 4, 'Entregar 10 cartões em mãos'),
  (20, 5, 'Entregar 25 flyers a residentes'),
  (20, 6, '2h de seguimento à base de dados'),
  (20, 7, 'Continuar entrega de blocos de notas'),
  (20, 8, 'Enviar relatório diário'),
  (21, 1, 'Inserir post nas redes (2ªf)'),
  (21, 2, 'Briefing com o gestor'),
  (21, 3, '2h de posicionamento na área'),
  (21, 4, 'Levantamento de área 16/30'),
  (21, 5, 'Entregar 10 cartões em mãos'),
  (21, 6, 'Entregar 25 flyers a residentes'),
  (21, 7, 'Verificar alertas de portais (FSBO)'),
  (21, 8, 'Definir dia fixo da Newsletter e aprender Sendinblue/Mailchimp'),
  (21, 9, 'Enviar relatório diário'),
  (22, 1, 'Briefing com o gestor'),
  (22, 2, 'Formação (3ªf)'),
  (22, 3, '2h de posicionamento na área'),
  (22, 4, 'Preparar posts de dias comemorativos'),
  (22, 5, 'Levantamento de área 17/30'),
  (22, 6, 'Entregar 10 cartões em mãos'),
  (22, 7, 'Entregar 25 flyers a residentes'),
  (22, 8, 'Definir plano anual de publicidade'),
  (22, 9, 'Enviar 10 sms a CIPs'),
  (22, 10, 'Enviar relatório diário'),
  (23, 1, 'Briefing com o gestor'),
  (23, 2, 'Saída de rua (4ª/5ª)'),
  (23, 3, '2h de posicionamento na área'),
  (23, 4, 'Post no Facebook'),
  (23, 5, 'Levantamento de área 18/30'),
  (23, 6, 'Entregar 10 cartões em mãos'),
  (23, 7, 'Entregar 25 flyers a residentes'),
  (23, 8, '2h de seguimento à base de dados'),
  (23, 9, 'Enviar relatório diário'),
  (24, 1, 'Briefing com o gestor'),
  (24, 2, 'Saída de rua (4ª/5ª)'),
  (24, 3, '2h de posicionamento na área'),
  (24, 4, 'Levantamento de área 19/30'),
  (24, 5, 'Entregar 10 cartões em mãos'),
  (24, 6, 'Entregar 25 flyers a residentes'),
  (24, 7, 'Contactar 10 CIPs na base'),
  (24, 8, 'Contactar 10 CIPs por messenger'),
  (24, 9, 'Enviar 10 sms a CIPs'),
  (24, 10, 'Enviar relatório diário'),
  (25, 1, 'Briefing com o gestor'),
  (25, 2, 'Reunião de equipe (6ªf quinzenal)'),
  (25, 3, '2h de posicionamento na área'),
  (25, 4, 'Levantamento de área 20/30'),
  (25, 5, 'Entregar 10 cartões em mãos'),
  (25, 6, 'Entregar 25 flyers a residentes'),
  (25, 7, '2h de seguimento à base de dados'),
  (25, 8, 'Continuar entrega de blocos de notas'),
  (25, 9, 'Assistir ao filme "Eddie the Eagle"'),
  (25, 10, 'Enviar relatório diário'),
  (26, 1, 'Inserir post nas redes (2ªf)'),
  (26, 2, 'Briefing com o gestor'),
  (26, 3, '2h de posicionamento na área'),
  (26, 4, 'Levantamento de área 21/30'),
  (26, 5, 'Entregar 10 cartões em mãos'),
  (26, 6, 'Entregar 25 flyers a residentes'),
  (26, 7, 'Verificar alertas de portais (FSBO)'),
  (26, 8, 'Preparar pesquisa sobre a área'),
  (26, 9, 'Enviar relatório diário'),
  (27, 1, 'Briefing com o gestor'),
  (27, 2, 'Formação (3ªf)'),
  (27, 3, '2h de posicionamento na área'),
  (27, 4, 'Preparar posts de dias comemorativos'),
  (27, 5, 'Levantamento de área 22/30'),
  (27, 6, 'Entregar 10 cartões em mãos'),
  (27, 7, 'Entregar 25 flyers a residentes'),
  (27, 8, 'Criar flyer "atacar placas da concorrência"'),
  (27, 9, 'Enviar 10 sms a CIPs'),
  (27, 10, 'Enviar relatório diário'),
  (28, 1, 'Briefing com o gestor'),
  (28, 2, 'Saída de rua (4ª/5ª)'),
  (28, 3, '2h de posicionamento na área'),
  (28, 4, 'Post no Facebook'),
  (28, 5, 'Levantamento de área 23/30'),
  (28, 6, 'Entregar 10 cartões em mãos'),
  (28, 7, 'Entregar 25 flyers a residentes'),
  (28, 8, '2h de seguimento à base de dados'),
  (28, 9, 'Fechar parceria com café (1 levantamento = 1 café)'),
  (28, 10, 'Enviar relatório diário'),
  (29, 1, 'Briefing com o gestor'),
  (29, 2, 'Saída de rua (4ª/5ª)'),
  (29, 3, '2h de posicionamento na área'),
  (29, 4, 'Levantamento de área 24/30'),
  (29, 5, 'Entregar 10 cartões em mãos'),
  (29, 6, 'Entregar 25 flyers a residentes'),
  (29, 7, 'Contactar 10 CIPs na base'),
  (29, 8, 'Contactar 10 CIPs por messenger'),
  (29, 9, 'Enviar 10 sms a CIPs'),
  (29, 10, 'Enviar relatório diário'),
  (30, 1, 'Briefing com o gestor'),
  (30, 2, '2h de posicionamento na área'),
  (30, 3, 'Levantamento de área 25/30'),
  (30, 4, 'Entregar 10 cartões em mãos'),
  (30, 5, 'Entregar 25 flyers a residentes'),
  (30, 6, '2h de seguimento à base de dados'),
  (30, 7, 'Continuar entrega de blocos de notas'),
  (30, 8, 'Enviar relatório diário'),
  (31, 1, 'Inserir post nas redes (2ªf)'),
  (31, 2, 'Briefing com o gestor'),
  (31, 3, '2h de posicionamento na área'),
  (31, 4, 'Levantamento de área 26/30'),
  (31, 5, 'Entregar 10 cartões em mãos'),
  (31, 6, 'Entregar 25 flyers a residentes'),
  (31, 7, 'Verificar alertas de portais (FSBO)'),
  (31, 8, 'Enviar flyers de parceria à gráfica'),
  (31, 9, 'Enviar relatório diário'),
  (32, 1, 'Briefing com o gestor'),
  (32, 2, 'Formação (3ªf)'),
  (32, 3, '2h de posicionamento na área'),
  (32, 4, 'Preparar posts de dias comemorativos'),
  (32, 5, 'Levantamento de área 27/30'),
  (32, 6, 'Entregar 10 cartões em mãos'),
  (32, 7, 'Entregar 25 flyers a residentes'),
  (32, 8, 'Colocar expositor A4/A5 na área (repor 2ªf / deixar 6ªf)'),
  (32, 9, 'Enviar 10 sms a CIPs'),
  (32, 10, 'Enviar relatório diário'),
  (33, 1, 'Briefing com o gestor'),
  (33, 2, 'Saída de rua (4ª/5ª)'),
  (33, 3, '2h de posicionamento na área'),
  (33, 4, 'Inserir post nas redes'),
  (33, 5, 'Levantamento de área 28/30'),
  (33, 6, 'Entregar 10 cartões em mãos'),
  (33, 7, 'Entregar 25 flyers a residentes'),
  (33, 8, 'Agendar próximo evento'),
  (33, 9, '2h de seguimento à base de dados'),
  (33, 10, 'Fechar parceria com cabeleireiro (1 flyer = 1 benefício)'),
  (33, 11, 'Enviar relatório diário'),
  (34, 1, 'Briefing com o gestor'),
  (34, 2, 'Saída de rua (4ª/5ª)'),
  (34, 3, '2h de posicionamento na área'),
  (34, 4, 'Levantamento de área 29/30'),
  (34, 5, 'Entregar 10 cartões em mãos'),
  (34, 6, 'Entregar 25 flyers a residentes'),
  (34, 7, 'Contactar 10 CIPs na base'),
  (34, 8, 'Contactar 10 CIPs por messenger'),
  (34, 9, 'Enviar 10 sms a CIPs'),
  (34, 10, 'Enviar relatório diário'),
  (35, 1, 'Briefing com o gestor'),
  (35, 2, 'Reunião de equipe (6ªf)'),
  (35, 3, '2h de posicionamento na área'),
  (35, 4, 'Levantamento de área 30/30 (conclui!)'),
  (35, 5, 'Entregar 10 cartões em mãos'),
  (35, 6, 'Entregar 25 flyers a residentes'),
  (35, 7, '2h de seguimento à base de dados'),
  (35, 8, 'Continuar entrega de blocos de notas'),
  (35, 9, 'Preparar distribuição de flyers'),
  (35, 10, 'Deixar publicidade 6ªf no comércio'),
  (35, 11, 'Enviar relatório diário');
